base_model: AIDC-AI/Marco-o1

load_in_8bit: false
load_in_4bit: false
strict: false

plugins:
  - axolotl.integrations.liger.LigerPlugin
liger_rope: true
liger_rms_norm: true
liger_swiglu: true
liger_fused_linear_cross_entropy: true

datasets:
  - path: datasets/Orca-Math-resort-unfiltered.jsonl
    type: sharegpt
  - path: datasets/dolphin-coder-codegen-sharegpt2.jsonl
    type: sharegpt
  - path: datasets/dolphin-coder-translate-sharegpt2.jsonl
    type: sharegpt
  - path: datasets/m-a-p_Code-Feedback-sharegpt-unfiltered.jsonl
    type: sharegpt
  - path: datasets/m-a-p_CodeFeedback-Filtered-Instruction-sharegpt-unfiltered.jsonl
    type: sharegpt
  - path: datasets/sharegpt_WRN-Chapter-1.jsonl
    type: sharegpt
  - path: datasets/sharegpt_WRN-Chapter-2.jsonl
    type: sharegpt
  - path: datasets/sharegpt_code-end-to-end-cyber.jsonl
    type: sharegpt
  - path: datasets/sharegpt_code-end-to-end-general.jsonl
    type: sharegpt



chat_template: chatml
shuffle_merged_datasets: true
val_set_size: 0.00005
output_dir: ./Retis-Coder-o1

sequence_len: 8192
sample_packing: true
eval_sample_packing: false
pad_to_sequence_len: true

# adapter: qlora
# lora_model_dir:
# lora_r: 32
# lora_alpha: 64
# lora_dropout: 0.05
# lora_target_linear: true
# lora_fan_in_fan_out:

wandb_project: Retis-Coder-o1
wandb_entity:
wandb_watch:
wandb_name: Unit v0.0
wandb_log_model:

unfrozen_parameters:
- ^lm_head.weight$
- ^model.embed_tokens.weight$
# input_layernorm layers
- model.layers.0.input_layernorm
- model.layers.1.input_layernorm
- model.layers.2.input_layernorm
- model.layers.3.input_layernorm
- model.layers.4.input_layernorm
- model.layers.5.input_layernorm
- model.layers.6.input_layernorm
- model.layers.7.input_layernorm
- model.layers.8.input_layernorm
- model.layers.9.input_layernorm
- model.layers.10.input_layernorm
- model.layers.11.input_layernorm
- model.layers.12.input_layernorm
- model.layers.13.input_layernorm
# lm_head layers
# mlp.down_proj layers
- model.layers.27.mlp.down_proj
- model.layers.20.mlp.down_proj
- model.layers.5.mlp.down_proj
- model.layers.6.mlp.down_proj
- model.layers.7.mlp.down_proj
- model.layers.22.mlp.down_proj
- model.layers.4.mlp.down_proj
- model.layers.18.mlp.down_proj
- model.layers.8.mlp.down_proj
- model.layers.14.mlp.down_proj
- model.layers.12.mlp.down_proj
- model.layers.10.mlp.down_proj
- model.layers.21.mlp.down_proj
- model.layers.3.mlp.down_proj
# mlp.gate_proj layers
- model.layers.18.mlp.gate_proj
- model.layers.8.mlp.gate_proj
- model.layers.6.mlp.gate_proj
- model.layers.20.mlp.gate_proj
- model.layers.7.mlp.gate_proj
- model.layers.27.mlp.gate_proj
- model.layers.12.mlp.gate_proj
- model.layers.15.mlp.gate_proj
- model.layers.26.mlp.gate_proj
- model.layers.11.mlp.gate_proj
- model.layers.25.mlp.gate_proj
- model.layers.10.mlp.gate_proj
- model.layers.21.mlp.gate_proj
- model.layers.17.mlp.gate_proj
# mlp.up_proj layers
- model.layers.18.mlp.up_proj
- model.layers.6.mlp.up_proj
- model.layers.14.mlp.up_proj
- model.layers.7.mlp.up_proj
- model.layers.15.mlp.up_proj
- model.layers.20.mlp.up_proj
- model.layers.8.mlp.up_proj
- model.layers.12.mlp.up_proj
- model.layers.10.mlp.up_proj
- model.layers.17.mlp.up_proj
- model.layers.11.mlp.up_proj
- model.layers.21.mlp.up_proj
- model.layers.22.mlp.up_proj
- model.layers.16.mlp.up_proj
# model.embed_tokens layers
# model.norm layers
# post_attention_layernorm layers
- model.layers.0.post_attention_layernorm
- model.layers.1.post_attention_layernorm
- model.layers.2.post_attention_layernorm
- model.layers.3.post_attention_layernorm
- model.layers.4.post_attention_layernorm
- model.layers.5.post_attention_layernorm
- model.layers.6.post_attention_layernorm
- model.layers.7.post_attention_layernorm
- model.layers.8.post_attention_layernorm
- model.layers.9.post_attention_layernorm
- model.layers.10.post_attention_layernorm
- model.layers.11.post_attention_layernorm
- model.layers.12.post_attention_layernorm
- model.layers.13.post_attention_layernorm
# self_attn.k_proj layers
- model.layers.0.self_attn.k_proj
- model.layers.10.self_attn.k_proj
- model.layers.24.self_attn.k_proj
- model.layers.7.self_attn.k_proj
- model.layers.17.self_attn.k_proj
- model.layers.3.self_attn.k_proj
- model.layers.20.self_attn.k_proj
- model.layers.21.self_attn.k_proj
- model.layers.5.self_attn.k_proj
- model.layers.23.self_attn.k_proj
- model.layers.25.self_attn.k_proj
- model.layers.2.self_attn.k_proj
- model.layers.11.self_attn.k_proj
- model.layers.8.self_attn.k_proj
# self_attn.o_proj layers
- model.layers.1.self_attn.o_proj
- model.layers.8.self_attn.o_proj
- model.layers.7.self_attn.o_proj
- model.layers.5.self_attn.o_proj
- model.layers.4.self_attn.o_proj
- model.layers.2.self_attn.o_proj
- model.layers.15.self_attn.o_proj
- model.layers.3.self_attn.o_proj
- model.layers.10.self_attn.o_proj
- model.layers.11.self_attn.o_proj
- model.layers.22.self_attn.o_proj
- model.layers.12.self_attn.o_proj
- model.layers.14.self_attn.o_proj
- model.layers.18.self_attn.o_proj
# self_attn.q_proj layers
- model.layers.21.self_attn.q_proj
- model.layers.26.self_attn.q_proj
- model.layers.14.self_attn.q_proj
- model.layers.17.self_attn.q_proj
- model.layers.22.self_attn.q_proj
- model.layers.16.self_attn.q_proj
- model.layers.12.self_attn.q_proj
- model.layers.11.self_attn.q_proj
- model.layers.20.self_attn.q_proj
- model.layers.18.self_attn.q_proj
- model.layers.8.self_attn.q_proj
- model.layers.24.self_attn.q_proj
- model.layers.15.self_attn.q_proj
- model.layers.13.self_attn.q_proj
# self_attn.v_proj layers
- model.layers.0.self_attn.v_proj
- model.layers.2.self_attn.v_proj
- model.layers.3.self_attn.v_proj
- model.layers.7.self_attn.v_proj
- model.layers.8.self_attn.v_proj
- model.layers.9.self_attn.v_proj
- model.layers.10.self_attn.v_proj
- model.layers.13.self_attn.v_proj
- model.layers.18.self_attn.v_proj
- model.layers.19.self_attn.v_proj
- model.layers.21.self_attn.v_proj
- model.layers.12.self_attn.v_proj
- model.layers.20.self_attn.v_proj
- model.layers.16.self_attn.v_proj

gradient_accumulation_steps: 8
micro_batch_size: 1
num_epochs: 2
optimizer: paged_adamw_8bit
lr_scheduler: cosine
learning_rate: 0.00003

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: "unsloth"
gradient_checkpointing_kwargs:
  use_reentrant: false
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 10
evals_per_epoch: 4
saves_per_epoch: 4
debug:
deepspeed: deepspeed_configs/zero3_bf16.json
weight_decay: 0.2
# fsdp:
#   - full_shard
#   - auto_wrap
# fsdp_config:
#   fsdp_limit_all_gathers: true
#   fsdp_sync_module_states: true
#   fsdp_offload_params: true
#   fsdp_use_orig_params: false
#   fsdp_cpu_ram_efficient_loading: true
#   fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
#   fsdp_transformer_layer_cls_to_wrap: Qwen2DecoderLayer
#   fsdp_state_dict_type: FULL_STATE_DICT
#   fsdp_sharding_strategy: FULL_SHARD
# special_tokens:
